### PR TITLE
chore(tests): add base for testing

### PR DESCRIPTION
**Pull request by alacambre-yseop**
− add modules and files for tests
− add laucher for the tests
− package won't work if tests are not ok

### CODE REVIEW

**Comment by mminot-yseop** [comment]
Jenkins does not seem very happy.

**Comment by alacambre-yseop** [comment]
Yep, server miss a specific package.

**Comment by mminot-yseop** [comment]
```bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell```
Seems to run fine otherwise.

**Comment by mminot-yseop** [comment]
I'll leave the Jenkins issues to @wjeanniard-yseop :yum:

**Pull request merged**
