### PR TITLE
chore(release): version 1.6.2

### PR DESCRIPTION
**Pull request by alacambre-yseop**

### CODE REVIEW

**Comment by mminot-yseop** [comment]
Again the “whitespace at the beginning of PR title” issue. Do we have a script that does that?

**Comment by alacambre-yseop** [comment]
Maybe I messed up somehow.

**Comment by mminot-yseop** [comment]
> Maybe I messed up somehow.

But it always seem to happen at the same moment xd

**Comment by alacambre-yseop** [comment]
Yeah, this is probably because I did a commit following this pattern:

chore(release): version 1.6.2
---------------------
chore(release): version 1.6.2

**Pull request merged**
