### PR TITLE
doc(snippets): add list and, in a comment, a command to update it

### PR DESCRIPTION
**Pull request by mminot-yseop**
Self-explanatory and trivial.

### CODE REVIEW

**Comment by alacambre-yseop** [comment]
I think the comments should be in the root README file. Also, there is nothing explaining what is jq nor how to get it.

**Comment by mminot-yseop** [comment]
I dunno… The root readme seems less contributors-oriented, to me. I wanted to intercept anyone who tried to change the client readme after having added a feature, so…
As for `jq`, they can look it up on the web, but I'll see what I can do…

**Comment by mminot-yseop** [comment]
Seriously, there's nothing even remotely related to features, snippets or contributions in the global readme.

**Comment by alacambre-yseop** [comment]
Well, there are a bunch of informations about antlr4 or syntax highlighting stuff. There are even informations about packaging. This is clearly contributors-oriented.

**Comment by mminot-yseop** [comment]
Still, a command meant to generate stuff for a given file should probably be show in the very same file.

I'm planning on adding a “Contributing” section to the global readme, but this brings new questions to the surface: for example: should the contributors update the client-readme themselves in their PRs, or should we do it ourselves during the releasing process?

**Comment by mminot-yseop** [comment]
Here…

**Pull request merged**
