### PR TITLE
feat: icons for yseopml files; .yml not yseopml

### PR DESCRIPTION
**Pull request by alacambre-yseop**
Please take some moments to test this.
Icons should be visible when the next version of VSCode (January 2022) is released (planned for February 03, 2022).
However, the extension should still work for older versions.

### CODE REVIEW

**Review by aauzimour-yseop — DISMISSED** [review]
nice-looking feature !

**Review by erobert-yseop — DISMISSED** [review]
So if I understand well, it's normal that I don't see the new icons
Otherwise I didn't see any issue :+1:

**Comment by aauzimour-yseop** [comment]
Yes for now I couldn't see it as well. Will be visible in a month or two.

**Comment by alacambre-yseop** [comment]
OK, so if we're lucky and I understand well, when you will update your version of VSCode you should see icons appear if you stick with the tested version of the extension.

**Comment by alacambre-yseop** [comment]
> Icons should be visible when the next version of VSCode (January 2022) is released (planned for February 03, 2022).

**Review by mminot-yseop — CHANGES_REQUESTED** [review]
SVG please. `fill="#blahblah"` in the `<path>` for yellow.

**Review by mminot-yseop — APPROVED** [review]
thx

**Pull request merged**
